<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Version>1.1.1</Version>
    <RepositoryUrl>https://github.com/Rintaro-Sugishita/FrostNova.Generators.MermaidClassGenerator</RepositoryUrl>
    <Authors>R.Sugishita</Authors>
    <ZipOutput>$(solutionDir)publish\FrostNova.Generators.MermaidClassGenerator_$(Version).zip</ZipOutput>
    <BaseOutputPath>$(solutionDir)bin</BaseOutputPath>
  </PropertyGroup>


  <Target Name="MyCheck" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <MakeDir Directories="$(solutionDir)publish" />    
    <ZipDirectory SourceDirectory="$(OutputPath)" DestinationFile="$(ZipOutput)" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.0.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\FrostNova.MmdClassDiagramBase\FrostNova.MmdClassDiagramBase.csproj" />
  </ItemGroup>

</Project>
